version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'

- run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

- run:
          name: Code 
          command: |
            ls -al
            echo '^^^hmm.., running code...^^^'

